services:
  db-prod:
    image: mysql:8
    container_name: escalation-league-db-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${PROD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROD_MYSQL_DATABASE}
      MYSQL_USER: ${PROD_MYSQL_USER}
      MYSQL_PASSWORD: ${PROD_MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_prod_data:/var/lib/mysql

  backend-prod:
    build:
      context: ./escalation-league-backend
      dockerfile: Dockerfile
    container_name: escalation-league-backend-prod
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://${PROD_MYSQL_USER}:${PROD_MYSQL_PASSWORD}@db-prod:3306/${PROD_MYSQL_DATABASE}
    env_file:
      - ./escalation-league-backend/.env.prod
    ports:
      - "3000:3000"
    depends_on:
      - db-prod

  frontend-prod:
    build:
      context: ./escalation-league-frontend
      dockerfile: Dockerfile
    container_name: escalation-league-frontend-prod
    environment:
      NODE_ENV: production
      API_URL: https://api.escalationleague.com
    ports:
      - "8080:80" # Map external port 8080 to internal port 80

  nginx-prod:
    image: nginx:latest
    container_name: escalation-league-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend-prod
      - frontend-prod

volumes:
  db_prod_data: