blank_issues_enabled: false
contact_links: []
issue_template:
  - name: "Bug Report"
    description: "Report a bug or unexpected behavior"
    labels: ["bug"]
    file: bug_report.md

  - name: "Feature Request"
    description: "Propose a new feature or improvement"
    labels: ["enhancement"]
    file: feature_request.md
